### ISSUE TITLE
Compile error on FPC 3.0 (lazarus 1.6)

### ISSUE THREAD

**Issue by alpermalas** [RRUZ/tsmbios#13]
This code does not work for FPC 3.0 (lazarus 1.6).

uSMBIOS.pas error on line number 5188
if {$IFDEF FPC} oEnum.Next(1, FWbemObject,nil) {$ELSE} oEnum.Next(1, FWbemObject, iValue) {$ENDIF} = 0 then

uSMBIOS.pas(5188,48) Error: Call by var for arg no. 3 has to match exactly: Got "Pointer" expected "LongWord"

I think the FPC unit (ActiveX) changed.

Best regards.

**Comment by RRUZ** [comment]
Thanks for this report, the issue was fixed.

**Comment by alpermalas** [comment]
Thanks a lot. This was pretty fast :)

Best regards.
